INSERT INTO Demo (name) VALUES ('hoi2');
INSERT INTO Demo (name) VALUES ('test');
INSERT INTO Demo (name) VALUES ('test');
INSERT INTO Demo (name) VALUES ('test');
INSERT INTO Demo (name) VALUES ('test');
INSERT INTO Demo (name) VALUES ('test');
INSERT INTO Demo (name) VALUES ('test');
INSERT INTO Demo (name) VALUES ('test');
INSERT INTO Person (name, age) VALUES ('hoi2', 13);
INSERT INTO Person (name, age) VALUES ('test', 94);
INSERT INTO Person (name, age) VALUES ('test', 55);
INSERT INTO Person (name, age) VALUES ('test', 75);
INSERT INTO Person (name, age) VALUES ('test', 51);
INSERT INTO Person (name, age) VALUES ('test', 25);
INSERT INTO Person (name, age) VALUES ('test', 35);
INSERT INTO Person (name, age) VALUES ('test', 56);